### ISSUE TITLE
something is happening

### ISSUE THREAD

**Issue by Lets-game6531** [amsam0/voicechat-discord#79] opened 2024-11-27 18:50 UTC
**Describe the bug**
when I talk on one side with dvc and the other with simple vc it works for a few seconds then stops working

**To Reproduce**
1. join the server on one account with simple voice chat
2. join the server on a account that doesn't have simple voice chat
3. on the second account do the command '/dvc start'
4. talk on both ends
5. then it stops working

**Expected behavior**
I expected it to work

**Screenshots**
![image](https://github.com/user-attachments/assets/42766a04-ad9e-49fd-9f0e-316a6893f3c9)

**Logs**
[18:36:07] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:15] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:17] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:22] [VoiceChatPacketProcessingThread/INFO]: [voicechat-discord] [DEBUG 3] packet is a EntitySoundPacketImpl
[18:36:22] [VoiceChatPacketProcessingThread/ERROR]: [voicechat] Uncaught exception in thread VoiceChatPacketProcessingThread
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandSender net.minecraft.world.entity.Entity.getBukkitSender(net.minecraft.commands.CommandSourceStack)'
	at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:59) ~[voicechat-discord-paper-3.0.5.jar:?]
	at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:84) ~[voicechat-discord-paper-3.0.5.jar:?]
	at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.DiscordBot.handlePacket(DiscordBot.java:285) ~[voicechat-discord-paper-3.0.5.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:383) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:431) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303) ~[voicechat-bukkit-2.5.25.jar:?]
	at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[voicechat-bukkit-2.5.25.jar:?]
[18:36:25] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:32] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:39] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:42] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:50] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:57] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:36:59] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:37:16] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 2] resetting sender for player with UUID 00000000-0000-0000-0009-01f32d9e2e9c
[18:37:29] [Server thread/INFO]: .Lets_game6531 issued server command: /dvc stop
[18:37:29] [voicechat-discord: Bot Stop for 00000000-0000-0000-0009-01f32d9e2e9c/INFO]: [voicechat-discord] [DEBUG 1] waiting for reset thread to end
[18:37:29] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 1] reset thread 1 interrupted
[18:37:29] [voicechat-discord: Reset Thread #1/INFO]: [voicechat-discord] [DEBUG 1] reset thread 1 ending
[18:37:29] [voicechat-discord: Sender Thread #1/INFO]: [voicechat-discord] [DEBUG 1] sender thread 1 ending

**Versions (please complete the following information):**
- Minecraft: 1.21.3
- Loader (paper, purpur, fabric, quilt, etc): paper
- Simple Voice Chat: voicechat-bukkit-2.5.25.jar
- Simple Voice Chat Discord Bridge: voicechat-discord-paper-3.0.5.jar

**Comment by amsam0** [comment] 2024-11-28 01:06
Thank you for the logs. I don't know when I'll have time to fix this, but I'll keep it in mind.

**Comment by Lets-game6531** [comment] 2024-12-22 16:49
when will you do the next update? and when will you update the plugin to 1.21.4?

**Comment by amsam0** [comment] 2024-12-22 17:42
#75. Pestering me about it makes me less likely to update it.

**Comment by amsam0** [comment] 2024-12-22 17:57
Closing as a duplicate of #76

**Closed** 2024-12-22 17:58 UTC
Labels: bug
