### ISSUE TITLE
Old glibc crashes addon

### ISSUE THREAD

**Issue by Limeen** [amsam0/voicechat-discord#63] opened 2024-08-01 06:32 UTC
**Describe the bug**

Plugin crashes on startup, Minecraft Paper 1.20.1 with the latest version of voicechat (2.5.16) and voicechat-discord (3.0.3)
Works fine on my personal computer, but can't start when on my host, i didn't had this problem when i used version 2.1.1 of voicechat-discord

**To Reproduce**
1. Install latest versions of voicechat and voicechat-discord on Paper/Purpur 1.20.1
2. Start the server
3. See error

**Expected behavior**
The plugin voicechat-discord crashes but not voicechat

**Logs**
- [jeu. 08:18:15 ERROR voicechat-discord] Failed to load natives: Could not load voicechat_discord natives for linux-x64
- [jeu. 08:18:15 ERROR Minecraft] Error occurred while enabling voicechat-discord v3.0.3 (Is it up to date?)
java.lang.RuntimeException: java.lang.Exception: Could not load voicechat_discord natives for linux-x64
    at voicechat-discord-paper-3.0.3.jar//dev.naturecodevoid.voicechatdiscord.Core.enable(Core.java:44)
    at voicechat-discord-paper-3.0.3.jar//dev.naturecodevoid.voicechatdiscord.PaperPlugin.onEnable(PaperPlugin.java:79)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656)
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567)
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1116)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.Exception: Could not load voicechat_discord natives for linux-x64
    at voicechat-discord-paper-3.0.3.jar//dev.naturecodevoid.voicechatdiscord.LibraryLoader.load(LibraryLoader.java:116)
    at voicechat-discord-paper-3.0.3.jar//dev.naturecodevoid.voicechatdiscord.Core.enable(Core.java:41)
    ... 13 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/voicechat_discord-03ed1695797cbcf75b845adb59294d6c/libvoicechat_discord.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/voicechat_discord-03ed1695797cbcf75b845adb59294d

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader (paper, purpur, fabric, quilt, etc): Purpur 
- Simple Voice Chat: 2.5.16
- Simple Voice Chat Discord Bridge: 3.0.3

**Comment by naturecodevoid** [comment] 2024-08-01 15:52
Duplicate of #54. Your host is running an old glibc. Can you try this nightly build: https://github.com/naturecodevoid/voicechat-discord/actions/runs/10201593043

**Comment by amsam0** [comment] 2024-08-15 17:39
@Limeen Any updates?

**Comment by amsam0** [comment] 2024-08-23 19:27
I'm going to close this issue since it would be a huge pain to fix it. Honestly, if your hosting provider doesn't respond to support tickets (in addition to using outdated servers), I would switch to a different one.

**Closed by amsam0** 2024-08-23 19:27 UTC
Labels: bug

**Comment by amsam0** [comment] 2025-11-26 17:18
This will be fixed in an upcoming 3.1.2 release (which will be released when 1.21.11 comes out). The new minimum glibc is 2.26. See #144 for a nightly build with the fixes

**Comment by Limeen** [comment] 2025-11-26 17:26
Thanks!
